### ISSUE TITLE
assert CC2650 launchpad with zigbee-shepherd

### ISSUE THREAD

**Issue by amigomcu** [zigbeer/zigbee-shepherd#15]
hi all,

in my test ,cc2538 ,it should be work .

but when i try znp CC2650 launchpad ,(build Coordinator_pro_secure_linkkeyjoin)

that have assert at ccznp.(that have been test by Z-tool)

have any one give me a advice about this? what type to select or ohter ?

at the doc with cc2630 znp, it have multi-type(coord/router and enddevice) and type(secure/linkeyjoin)

ZNP hex files for CC2630/50 are named as follows:

znp_(Coordinator|Router|EndDev)_pro[_secure][_linkkeyjoin].hex

===============================================================================
(Coordinator|Router|EndDev) : This component of the name identifies what type
of ZigBee device functionality this hex file supports.

_pro : Indicates support for Zigbee PRO

[_secure] : If present, this hex file is to be used with ZNP applications that 
use standard ZigBee security where the NWK key is sent in the clear or is 
pre-configured. When using this image, the host processor must register for 
specific ZDO callbacks using the ZDO_MSG_CB_REGISTER API, and will be notified 
of the response via the ZDO_MSG_CB_INCOMING command.

[_linkkeyjoin] : If present, this hex file is to be used with ZNP applications 
that use the Pre-configured Trust Center Link Key method of joining where the 
pre-configured trust center link key is used to encrypt the APS tunnel 
command which contains the NWK key. When using this image, the host processor 
must register for specific ZDO callbacks using the ZDO_MSG_CB_REGISTER API,
and will be notified of the response via the ZDO_MSG_CB_INCOMING command. 
===============================================================================

sdk:
zstack_home_1_02_02a_4453

  zigbee-shepherd:init Coordinator initialize had an error: Error: rsp error: 2
    at rspHdlr (/home/user/zigbee-shepherd/lib/components/controller.js:273:29)
    at CcZnp.<anonymous> (/home/user/zigbee-shepherd/node_modules/cc-znp/lib/ccznp.js:257:13)
    at CcZnp.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at CcZnp.emit (events.js:188:7)
    at CcZnp._mtIncomingDataHdlr (/home/user/zigbee-shepherd/node_modules/cc-znp/lib/ccznp.js:357:14)
    at /home/user/zigbee-shepherd/node_modules/cc-znp/lib/ccznp.js:333:22
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) +2ms
shepherd start
Error: Coordinator has not been initialized yet.
    at /home/user/zigbee-shepherd/lib/shepherd.js:248:19
    at _fulfilled (/home/user/zigbee-shepherd/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/user/zigbee-shepherd/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/user/zigbee-shepherd/node_modules/q/q.js:816:13)
    at /home/user/zigbee-shepherd/node_modules/q/q.js:570:49
    at runSingle (/home/user/zigbee-shepherd/node_modules/q/q.js:137:13)
    at flush (/home/user/zigbee-shepherd/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  zigbee-shepherd:msgHdlr IND <-- SYS:resetInd +2m
exit

**Comment by jackchased** [comment]
We have not tried cc2650 yet, but we will spend some time to test the firmware lately.

I think this error perhaps is the NV works differently on the CC26xx, you can try to comment out this code at [controller.js L219-L222](https://github.com/zigbeer/zigbee-shepherd/blob/master/lib/components/controller.js#L219-L222).

**Comment by AlsonVamp** [comment]
May be someone will find it helpfull: To run zigbee-shepherd with CC2650 Launchpad as ZNP, I removed one line https://github.com/zigbeer/zigbee-shepherd/blob/master/lib/components/controller.js#L234 and server started as should.
