### ISSUE TITLE
Error: Unhandled "error" event. (Cannot get the Node Descriptor of the Device

### ISSUE THREAD

**Issue by aivs** [zigbeer/zigbee-shepherd#55]
Sometimes Shepherd crashes when I'm trying to add Xiaomi devices: WXKG03LM, WXKG02LM
```
19
18
17
16
/home/pi/node_modules/q/q.js:155
                throw e;
                ^

Error: Unhandled "error" event. (Cannot get the Node Descriptor of the Device: 0x00158d00015efcef)
    at ZShepherd.emit (events.js:186:19)
    at /home/pi/node_modules/zigbee-shepherd/lib/components/controller.js:609:28
    at _rejected (/home/pi/node_modules/q/q.js:864:24)
    at /home/pi/node_modules/q/q.js:890:30
    at Promise.when (/home/pi/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/pi/node_modules/q/q.js:808:41)
    at /home/pi/node_modules/q/q.js:624:44
    at runSingle (/home/pi/node_modules/q/q.js:137:13)
    at flush (/home/pi/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
```

**Comment by aivs** [comment]
I'm solved the problem.
If start with debug:
`sudo DEBUG=* node zigbee-server.js`

Shows slow including process
